Repository depromeet/pingpong-be, pull requests merged in 2022-12, with the labels that each got.

#41 등급 목록 조회 구현
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/application/MemberQueryService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/RanksListResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/RanksResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/presentation/MemberController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/PostListResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/PostReadResponse.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Ranks.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/enums/Ranks.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/enums/TalentType.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/MemberTalent.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/enums/TalentType.java
Labels: enhancement

#44 사용자 별 포스트 조회 API 구현
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/controller/PostController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/MyPagePostListResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/MyPagePostResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/dto/post/MyPagePostDto.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/CustomPostRepository.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/impl/CustomPostRepositoryImpl.java
Labels: enhancement

#69 코드 리팩토링
  winwin-be-api/build.gradle
  winwin-be-api/src/docs/asciidoc/category-api.adoc
  winwin-be-api/src/docs/asciidoc/index.adoc
  winwin-be-api/src/docs/asciidoc/member-api.adoc
  winwin-be-api/src/docs/asciidoc/post-api.adoc
  winwin-be-api/src/docs/asciidoc/report-api.adoc
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberQueryService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/controller/PostController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/MyPagePostListResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/PostResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/category/controller/CategoryControllerTest.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
Labels: refactor

#85 현재 로그인한 사용자 정보를 반환해주는 API 추가
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
Labels: feature

#87 s3 연동 및 회원 프로필 이미지 업로드 구현
  winwin-be-api/build.gradle
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/constant/ImageType.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/enums/ErrorMessage.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/file/service/AwsS3FileService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/file/service/FileService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/AwsS3Config.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/request/MemberUpdateRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberUpdateImageResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
  winwin-be-api/src/main/resources/application-local.yml
  winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
  winwin-be-api/src/test/resources/application.yml
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/dto/member/MemberUpdateDto.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
Labels: enhancement

#88 코드 리팩토링
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/response/dto/GlobalPageResponseDto.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
Labels: refactor

#92 좋아요 등록/취소 구현
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/enums/ErrorMessage.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberQueryService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/controller/PostController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/request/LikeAddRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/LikesResponse.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/LikesService.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/enums/Ranks.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Likes.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/LikesRepository.java
Labels: enhancement

#94 REST Docs API 문서 리팩토링
  winwin-be-api/src/docs/asciidoc/category-api.adoc
  winwin-be-api/src/docs/asciidoc/member-api.adoc
  winwin-be-api/src/docs/asciidoc/post-api.adoc
  winwin-be-api/src/docs/asciidoc/report-api.adoc
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
  winwin-be-api/src/main/resources/application-local.yml
  winwin-be-api/src/test/java/com/dpm/winwin/api/category/controller/CategoryControllerTest.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/report/controller/ReportControllerTest.java
Labels: refactor

#95 domain 모듈 테스트 환경 세팅
  build.gradle
  winwin-be-api/build.gradle
  winwin-be-api/src/test/resources/application.yml
  winwin-be-domain/src/test/java/com/dpm/winwin/domain/WinwinDomainApplication.java
  winwin-be-domain/src/test/java/com/dpm/winwin/domain/WinwinDomainApplicationTests.java
  winwin-be-domain/src/test/java/com/dpm/winwin/domain/configuration/JpaConfigurationTest.java
  winwin-be-domain/src/test/resources/application.yml
Labels: enhancement

#97 request validation 처리
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/enums/ErrorMessage.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/exception/GlobalExceptionHandler.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/request/MemberNicknameRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/request/MemberUpdateRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/controller/PostController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/request/PostAddRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/request/PostUpdateRequest.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
  winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/dto/request/MemberNicknameRequest.java
Labels: enhancement

#90 chore : 쿠키 옵션 설정
  .github/CODEOWNERS
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
Labels: refactor

#104 chore: aws beanstalk 설정
  .github/workflows/deploy.yml
  winwin-be-api/Dockerfile
  winwin-be-api/Dockerrun.aws.json
  winwin-be-api/src/main/resources/application-prod.yml
Labels: ci/cd, configuration

#101 feat : 로그아웃 설정
  winwin-be-api/build.gradle
  winwin-be-api/src/main/java/com/dpm/winwin/api/auth/controller/AuthController.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/auth/service/AuthService.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/common/response/dto/BaseResponseDto.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/jwt/JwtFilter.java
  winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/service/AppleLoginService.java
  winwin-be-api/src/main/resources/application-local.yml
  winwin-be-domain/build.gradle
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/RefreshToken.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/token/ExpiredToken.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/token/RefreshTokenEntity.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/RefreshTokenRepository.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/impl/CustomMemberRepositoryImpl.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/token/ExpiredTokenRepository.java
  winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/token/JwtTokenRepository.java
Labels: feature
